[package]
name = "systemd-manager"
version = "0.4.7"
license = "MIT"
authors = ["Michael Aaron Murphy <mmstickman@gmail.com>"]
description = "A GTK3 GUI for managing systemd services on Linux"
keywords = [ "gtk", "linux", "systemd" ]
repository = "https://github.com/mmstick/systemd-manager"
readme = "README.md"

[package.metadata.deb]
maintainer = "Michael Aaron Murphy <mmstickman@gmail.com>"
copyright = "2015-2016, Michael Aaron Murphy <mmstickman@gmail.com>"
license_file = ["LICENSE", "3"]
depends = "libc6, libgtk-3-0 (>= 3.16)"
section = "admin"
priority = "optional"
assets = [
    ["assets/org.freedesktop.policykit.systemd-manager.policy", "usr/share/polkit-1/actions/", "644"],
    ["assets/systemd-manager.desktop", "usr/share/applications/", "644"],
    ["assets/systemd-manager-pkexec", "usr/bin/", "755"],
    ["target/release/systemd-manager", "usr/bin/", "755"]
]

[dependencies]
dbus = "0.3.3"
gtk = { git = "https://github.com/gtk-rs/gtk.git", features = ["v3_16"] }
gdk = { git = "https://github.com/gtk-rs/gdk.git" }
quickersort = "2.0.1"

[profile.release]
opt-level = 3
lto = true
